name: Deploy Built Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Delete existing built branch if it exists
        run: |
          # Delete remote branch if it exists
          git push origin --delete main-built || true
          # Delete local branch if it exists
          git branch -D main-built || true

      - name: Create fresh orphan built branch
        run: |
          git checkout --orphan main-built
          # Clear the index for orphan branch
          git rm -rf . || true

      - name: Copy source files to built branch
        run: |
          # Copy all files from main branch except development files
          git checkout main -- .
          
          # Remove development-only files and directories
          rm -rf node_modules/ || true
          rm -rf tests/ || true
          rm -rf playwright/ || true
          rm -rf playwright-report/ || true
          rm -rf .github/ || true
          rm -rf src/ || true
          rm -f package.json || true
          rm -f package-lock.json || true
          rm -f playwright.config.ts || true
          rm -f .wp-env.json || true
          rm -f .editorconfig || true
          rm -f .gitignore || true
          rm -f CLAUDE.md || true
          rm -f README.md || true
          
          # Ensure build artifacts are present (they should be from the build step)
          ls -la

      - name: Commit & push to built branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: update built artifacts"
            git push --force origin main-built
          fi
