name: Deploy to WordPress.org

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: WordPress Plugin Deploy
        id: wp-deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: kaigen

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.wp-deploy.outputs.zip-path }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false 