name: Deploy Built Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Create or update built branch from main
        run: |
          # Check if built branch exists remotely
          if git ls-remote --heads origin main-built | grep -q main-built; then
            # Branch exists, check it out
            git checkout main-built
            # Reset to match main exactly (preserving history)
            git reset --hard main
          else
            # Branch doesn't exist, create it from main
            git checkout -b main-built
          fi

      - name: Remove development files and commit built version
        run: |
          # Remove development-only files and directories
          rm -rf node_modules/ || true
          rm -rf tests/ || true
          rm -rf playwright/ || true
          rm -rf playwright-report/ || true
          rm -rf .github/ || true
          rm -rf src/ || true
          rm -f package.json || true
          rm -f package-lock.json || true
          rm -f playwright.config.ts || true
          rm -f .wp-env.json || true
          rm -f .editorconfig || true
          rm -f .gitignore || true
          rm -f CLAUDE.md || true
          rm -f README.md || true
          
          # Ensure build artifacts are present
          ls -la

      - name: Commit & push built version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: update built artifacts (remove dev files)"
            git push --force origin main-built
          fi
