name: Deploy and Release Plugin

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  actions: read

jobs:
  # Update readme and assets only (runs on main branch pushes)
  update-assets:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: kaigen

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      # Create version tag if it doesn't exist when pushing to main
      - name: Create version tag
        if: github.ref == 'refs/heads/main'
        # no extra env needed
        run: |
          VERSION=$(grep -E "Version:\s*[0-9]+\.[0-9]+\.[0-9]+" kaigen.php \
                    | sed -E 's/.*Version:\s*([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "Current version: $VERSION"

          if ! git rev-parse "v$VERSION" >/dev/null 2>&1; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git tag "v$VERSION"
            git push origin "v$VERSION"
          else
            echo "Tag v$VERSION already exists"
          fi
